# Generated by Django 5.2.10 on 2026-02-17 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_medicine_supplier_alter_staff_role_pharmacybill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Receptionist', 'Receptionist'), ('Lab Technician', 'Lab Technician'), ('Pharmacist', 'Pharmacist'), ('Driver', 'Driver')], max_length=50),
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Basic', 'Basic Life Support (BLS)'), ('ICU', 'Advanced Life Support (ICU)'), ('Oxygen', 'Patient Transport (Oxygen)')], max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.OneToOneField(blank=True, limit_choices_to={'role': 'Driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ambulance', to='myapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=15)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.ambulance')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_trips', to='myapp.staff')),
            ],
        ),
    ]
