# Generated by Django 6.0 on 2026-01-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Receptionist', 'Receptionist'), ('Lab Technician', 'Lab Technician')], max_length=50),
        ),
    ]
